id: PA8EE6EBD
initial_creation_type: input
source_metadata:
  title: Pawo Lerab Tsal Series
  language: bo
  description: 'Texts by and about the eighteenth century treasure-revealer Pawo Lerab
    Tsal (dpa'' bo las rab rtsal) alias Cheyöl Rigdzin Chenmo (che yol rig ''dzin
    chen mo):'
  volume:
    4550f0e0ecf1472795b9eb11faab5057:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Guru Rinpoche Prayers
created_at: '2022-03-01T01:15:08.513744'
last_modified_at: '2022-03-01T01:15:08.513746'
